# Node.js 23 (Alpineベース) イメージを使用
FROM node:23-alpine

# コンテナ内部の作業ディレクトリ
WORKDIR /usr/src/frontend

# nextアプリが用意できた後、戻す
# package.jsonとpackage-lock.jsonをコピー
# COPY ./frontend/package*.json ./

# RUN npm install